TOPDIR = $(abspath ../..)

NAME	= libmultiplex.a

LIBS	= \

SRCS	= \
	io_event.cpp \
	multiplex.cpp

# **************************************************************************** #
include $(TOPDIR)/build/Rules.mk

CPPFLAGS	+=
CXXFLAGS	+=
LDFLAGS		+=
LDLIBS		+=

$(NAME): $(OBJS)
	$(AR) $(ARFLAGS) $@ $^
